title: dkn.su
description: dkn group hub & blog
url: "https://dkn.su"
markdown: kramdown
permalink: /blog/:title.html
exclude:
  - README.md
  - CNAME
  - build.py
  - serve.py
  - start.bat
  - requirements.txt
  - Gemfile.lock
